server:
  port: :8080

mysql:
  host: localhost
  port: 3306
  database: test
  username: root
  password: 123456
  charset: utf8mb4
redis:
  host: localhost
  port: 6379
  password: 
#  masterName: redis-master

log:
  name: test-user-api #logger的名称
  development: false # 是否开启开发模式，开发模式下会打印调试信息，默认 false
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: json # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths: logs/test-user-api # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件。
  error-output-paths: logs/test-user-api # zap内部(非业务)错误日志输出路径，多个输出，逗号分开

es:
  host: 172.0.0.1
  port: 9200