server:
  port: :8080

mysql:
  host: localhost
  port: 3306
  database: test
  username: root
  password: 123456
  charset: utf8mb4
redis:
  host: localhost
  port: 6379
  password: 
#  masterName: redis-master